# Generated by Django 5.2.5 on 2025-08-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=16)),
                ('high', models.DecimalField(decimal_places=6, max_digits=16)),
                ('low', models.DecimalField(decimal_places=6, max_digits=16)),
                ('close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('volume', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'date'], name='marketdata__company_7a9232_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
