# Generated by Django 5.2.5 on 2025-08-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebar',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricebar',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pricebar',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricebar',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricebar',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricebar',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pricebar',
            index=models.Index(fields=['date'], name='marketdata__date_559159_idx'),
        ),
    ]
