# Generated by Django 5.2.5 on 2025-08-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('IS', 'Income'), ('BS', 'Balance'), ('CF', 'Cashflow')], max_length=2)),
                ('period_end', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('Q', 'Quarter'), ('Y', 'Year')], max_length=1)),
                ('json_payload', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('period_end', models.DateField(db_index=True)),
                ('period_type', models.CharField(choices=[('Q', 'Quarter'), ('TTM', 'TTM')], max_length=4)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'key', 'period_end'], name='fundamental_company_9ca67c_idx')],
            },
        ),
    ]
