# Generated by Django 5.2.5 on 2025-08-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('definition_json', models.JSONField()),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('snapshot_json', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rankings.ranking')),
            ],
            options={
                'indexes': [models.Index(fields=['ranking', 'rank'], name='rankings_ra_ranking_9db274_idx')],
                'unique_together': {('ranking', 'company')},
            },
        ),
    ]
